apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-app
          image: goltaraya/redis-app:v1
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
          - containerPort: 8080
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-app
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 8081
    targetPort: 8080
    
  